import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/Footer/Footer";
import AuthProvider from "@/providers/AuthProvider";
import AuthSyncProvider from "@/providers/AuthSyncProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <AuthSyncProvider>
          <Header />
          <div className="bg-babyshopLightBg pb-20">{children}</div>
          <Footer />
        </AuthSyncProvider>
        </AuthProvider>

        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
